### ISSUE TITLE
Namenskonflikt codenius

### ISSUE THREAD

**Issue by serkancodenius** [codenius/codenius.github.io#1]
Hallo zusammen],

ich hoffe, diese Nachricht erreicht Sie wohlauf.

Wir möchten Sie darauf aufmerksam machen, dass wir den Namen "Codenius" als Wortmarke gesetzlich schützen lassen haben. Unser Unternehmen hat erhebliche Anstrengungen und Ressourcen in die Entwicklung und den Schutz dieser Marke investiert, um sicherzustellen, dass sie für unsere Produkte und Dienstleistungen steht und von unseren Kunden eindeutig erkannt und geschätzt wird.

Im Rahmen unseres Markenschutzes gemäß dem deutschen Markengesetz (MarkenG) sowie der entsprechenden internationalen Regelungen ist es uns wichtig, dass keine Verwechslungen hinsichtlich der Herkunft von Produkten oder Dienstleistungen entstehen, die unter diesem Namen angeboten werden. Insbesondere möchten wir sicherstellen, dass der Name "Codenius" nicht unrechtmäßig von Dritten verwendet wird, um das Vertrauen und die Reputation unserer Marke zu wahren.

Da wir festgestellt haben, dass Ihre Organisation auf GitHub ebenfalls den Namen "Codenius" nutzt, möchten wir Sie höflich, aber eindringlich bitten, diesen Namen zu ändern. Dies ist erforderlich, um mögliche Verwechslungen und rechtliche Konflikte zu vermeiden.

Gemäß § 14 des deutschen Markengesetzes haben wir das ausschließliche Recht, die Verwendung unserer eingetragenen Marke zu untersagen, wenn diese für ähnliche Waren oder Dienstleistungen genutzt wird und die Gefahr besteht, dass das Publikum diese Zeichen/Wort miteinander verwechselt. Darüber hinaus können wir gemäß § 15 MarkenG Unterlassungsansprüche geltend machen und im Falle einer unberechtigten Nutzung Schadensersatzansprüche verfolgen.

Wir schätzen Ihre Zusammenarbeit in dieser Angelegenheit und sind überzeugt, dass wir gemeinsam eine einvernehmliche Lösung finden können. Wir bitten Sie daher, den Namen Ihrer Organisation innerhalb der nächsten 14 Tage zu ändern und uns darüber zu informieren. Sollten Sie innerhalb dieser Frist keine Maßnahmen ergreifen, sehen wir uns leider gezwungen, rechtliche Schritte einzuleiten, um unsere Marke zu schützen.

Für Rückfragen stehen wir Ihnen selbstverständlich gerne zur Verfügung unter info@codenius.de. Wir hoffen auf Ihr Verständnis und Ihre Kooperationsbereitschaft und verbleiben

mit freundlichen Grüßen,
Serkan Cihan
CEO 
codenius UG

Wir hoffen, dass wir diese Angelegenheit auf freundliche Weise klären können und danken Ihnen im Voraus für Ihre Mithilfe.

**Comment by serkancodenius** [comment]
Hallo nochmal,

falls du keine Organisation hast bitte verstehe diese Mail nicht als Angriff. Du kannst gerne deinen Namen leicht umändern sodass wir aber codenius nutzen können. 

Privaten Entwicklern möchten wir keinesfalls ein Stein legen.

Viele Grüße
Serkan

**Comment by codenius** [comment]
Hallo Herr Cihan,

Meiner Einschätzung nach stellt die die Nutzung des Benutzernamens keine markenmäßige Nutzung dar, da keine geschäftsmäßige sondern rein private Nutzung erfolgt. Weiterhin nimmt mein Auftritt in keiner Weise Bezug auf sie oder könnte anderweitig Verwirrung stiften. Außerdem habe bin ich zeitlich sehr viel früher mit dem Namen aufgetreten. Daher könnte vielmehr die Eintragung ihrerseits eine Beschränkung meiner Rechte darstellen. Schlussendlich sehen auch die GitHub-Richtlinien vor, das Benutzernamen nach dem Prioritätsprinzip („Wer zuerst kommt, mahlt zuerst“) vergeben werden. Explizit stellt auch eine geschützte Marke als Name grundsätzlich keine Markenverletzung dar und auch nicht im speziellen, weil kein Irreführung (bspw. durch gefälschte Auftritte in ihrem Namen o.ä.) vorliegen.

Ich wünsche ihrem Unternehmen weiterhin viel Erfolg und hoffe das sie einen anderen geeigneten Namen finden (codeniusUG und codenius-de wären zum Beispiel frei).

**Comment by serkancodenius** [comment]
vielen Dank für Ihre Rückmeldung.

Ich verstehe, dass Ihre Nutzung des Namens „Codenius“ auf GitHub rein privat ist. Unter diesen Umständen können Sie den Namen dort gerne weiter verwenden. Wir nutzen codeniuscompany als workspace. Falls Sie Interesse haben den github Namen an uns zu übertragen melden sie sich gerne unter info@codenius.de.

Es ist jedoch wichtig zu betonen, dass „Codenius“ als Marke gesetzlich geschützt ist. Sollten Sie in Erwägung ziehen, den Namen in irgendeiner Form geschäftlich zu nutzen, bitte ich Sie, sich umgehend bei uns zu melden. In einem solchen Fall müssten wir prüfen, ob eine Verletzung unserer Markenrechte vorliegt, da wir das exklusive Recht an der geschäftlichen Nutzung dieses Namens haben.

Ich hoffe, dass dies zu einem klaren Verständnis unserer jeweiligen Positionen beiträgt. Wir schätzen Ihre Kooperation und stehen Ihnen für weitere Fragen gerne zur Verfügung.

Mit freundlichen Grüßen,
Serkan Cihan
CEO, Codenius UG
